// import './components/image.js';
import './components/modalDestroy.js'
import './components/formValidation.js'
import './components/title.js'
import './components/menuHamburguer.js'
import './components/filterModal.js'
import './components/tableRecords.js'
import './components/form.js'
import './components/modalNotifiaction.js'
import './components/modalGallery.js'
import './components/uploadImage.js'
import './components/knm.js'
// import './components/modalErrors.js'
